### ISSUE TITLE
Exception connecting to the broker

### ISSUE THREAD

**Issue by FrankDoersam** [netonjm/HapSharp#3]
Hello,
thank you for this great projekt.
i get the following error:

![unbenannt](https://user-images.githubusercontent.com/16541879/36773321-57f2fc54-1c59-11e8-8699-ed6ad3ef5d34.PNG)

Coud you please help me :)

Best regared
Frank

**Comment by netonjm** [comment]
Hello! this issue happens because you need a broker running in background before executing your session. 
You can execute in another terminal the Broker project included in the solution or install any other Broker project like a service, in Mac or Linux Mosquitto works very well.

How was the setup in Windows? I didn't tried yet!

**Comment by netonjm** [comment]
I improved our connection logic adding a default 5 tries (also added a better message output). This will be enough to wait until you want execute the broker in the current solution.

https://github.com/netonjm/HapSharp/commit/ec972aa4b14a8376407f037d4d3e984da9e5ec77

The change is available in master.

**Comment by FrankDoersam** [comment]
Thank you!

**Comment by FrankDoersam** [comment]
You could close the request...
